app:
  rabbitmq:
    exchange: message.exchange
    routing-key: message.routing-key
    queue: message.queue
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
